"""
Build script for Screen Translator Windows installer.
Requires: PyInstaller, Inno Setup (installed on Windows)

Usage:
    python installer/build.py
"""
import os
import sys
import shutil
import subprocess
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).parent.parent
SRC_DIR = ROOT_DIR / "src"
BUILD_DIR = ROOT_DIR / "build"
DIST_DIR = ROOT_DIR / "dist"
INSTALLER_DIR = ROOT_DIR / "installer"
OUTPUT_DIR = INSTALLER_DIR / "Output"

APP_NAME = "ScreenTranslator"
APP_VERSION = "1.0.0"
MAIN_SCRIPT = SRC_DIR / "main.py"

INNO_SETUP_PATH = r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"


def clean():
    """Remove previous build artifacts."""
    for d in [BUILD_DIR, DIST_DIR]:
        if d.exists():
            shutil.rmtree(d)
            print(f"Cleaned: {d}")


def build_exe():
    """Run PyInstaller to create single-folder build."""
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", APP_NAME,
        "--windowed",
        "--onedir",
        "--clean",
        "--add-data", f"{SRC_DIR / 'resources'};resources",
        "--hidden-import", "PyQt6.QtCore",
        "--hidden-import", "PyQt6.QtGui",
        "--hidden-import", "PyQt6.QtWidgets",
        "--hidden-import", "qasync",
        "--hidden-import", "mss",
        "--hidden-import", "PIL",
        "--hidden-import", "httpx",
        "--hidden-import", "sqlite3",
        str(MAIN_SCRIPT),
    ]

    print("Building executable with PyInstaller...")
    result = subprocess.run(cmd, cwd=ROOT_DIR)
    if result.returncode != 0:
        print("PyInstaller failed!")
        sys.exit(1)
    print("Executable built successfully.")


def create_iss():
    """Generate Inno Setup script."""
    iss_content = f"""
; Screen Translator Inno Setup Script
; Auto-generated by build.py

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "Screen Translator"
#define MyAppURL "https://github.com/OWNER/screen-translator"
#define MyAppExeName "{APP_NAME}.exe"
#define MyAppDir "{DIST_DIR / APP_NAME}"

[Setup]
AppId={{{{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={OUTPUT_DIR}
OutputBaseFilename=ScreenTranslatorSetup
SetupIconFile=
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "arabic"; MessagesFile: "compiler:Languages\\Arabic.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked
Name: "startupicon"; Description: "تشغيل عند بدء ويندوز"; GroupDescription: "خيارات إضافية"; Flags: unchecked

[Files]
Source: "{{#MyAppDir}}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{commondesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon
Name: "{{userstartup}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: startupicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: dirifempty; Name: "{{app}}"
"""
    iss_path = INSTALLER_DIR / f"{APP_NAME}.iss"
    iss_path.write_text(iss_content, encoding="utf-8")
    print(f"Generated ISS script: {iss_path}")
    return iss_path


def build_installer(iss_path: Path):
    """Run Inno Setup compiler."""
    if not Path(INNO_SETUP_PATH).exists():
        print(f"Inno Setup not found at: {INNO_SETUP_PATH}")
        print("Skipping installer creation. Install Inno Setup 6 to create the installer.")
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [INNO_SETUP_PATH, str(iss_path)]
    print("Building installer with Inno Setup...")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print("Inno Setup failed!")
        sys.exit(1)
    print(f"Installer created: {OUTPUT_DIR / 'ScreenTranslatorSetup.exe'}")


def main():
    print(f"Building {APP_NAME} v{APP_VERSION}")
    print("=" * 50)

    clean()
    build_exe()
    iss_path = create_iss()

    if sys.platform == "win32":
        build_installer(iss_path)
    else:
        print("Not on Windows — skipping Inno Setup step.")
        print(f"ISS script ready at: {iss_path}")
        print(f"PyInstaller output: {DIST_DIR / APP_NAME}")

    print("=" * 50)
    print("Build complete!")


if __name__ == "__main__":
    main()
